# Generated by Django 3.2.15 on 2022-08-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_resource_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
