# Generated by Django 3.2.15 on 2022-08-04 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_alter_resource_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='resources',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='tags', to='directory.resource'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
