# Generated by Django 3.2.15 on 2022-08-04 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_auto_20220804_0922'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
