# Generated by Django 3.2.15 on 2022-08-04 10:10

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('directory', '0005_delete_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='tags',
            field=taggit.managers.TaggableManager(
                help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='slug',
            field=models.SlugField(
                editable=False, max_length=200, unique=True),
        ),
    ]
