# Generated by Django 3.2.15 on 2022-08-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0007_alter_resource_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
