# Generated by Django 3.2.15 on 2022-08-04 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0008_alter_resource_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='status',
            new_name='approved',
        ),
    ]
