# Generated by Django 3.2.15 on 2022-08-04 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0009_rename_status_resource_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_added',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='user_added',
            new_name='author',
        ),
    ]
