# Generated by Django 3.2.15 on 2022-08-18 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0011_auto_20220818_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='link_github',
            new_name='username_github',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='link_twitter',
            new_name='username_twitter',
        ),
    ]
