# Generated by Django 3.2.15 on 2022-08-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0012_auto_20220818_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='website_address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
