# Generated by Django 3.2.15 on 2022-08-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0013_profile_website_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username_github',
            field=models.CharField(blank=True, max_length=39, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username_twitter',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='website_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
